# Colors (Gruvbox Material Hard Dark)

# Default colors
[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc2418'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#68986a'
white   = '#a89984'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#83d69b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

# Font configuration
[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }

# Window settings
[window]
dimensions = { columns = 120, lines = 30 }
decorations = "Full"
padding = { x = 10, y = 10 }
dynamic_padding = true
blur = true
opacity = 0.90

# Shell: launch fish as the terminal shell
[terminal.shell]
program = "fish"